# Site settings
title: amyhua
email: foramyhua@gmail.com
description: "Amy Hua: developer, data geek, ideas person."
baseurl: ""
url: "http://amyhua.me"
twitter: 'amyhuaster'
github: 'amyhua'

auto: true

# Build settings
markdown: kramdown
permalink: pretty
gems: [sass]
